apiVersion: v1
kind: Service
metadata:
  name: mcss-mc-ssr
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mc-ssr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "mc-ssr.selectorLabels" . | nindent 4 }}
